### ISSUE TITLE
Switch 0.3.1 inactive for me in Joomla 5.1

### ISSUE THREAD

**Issue by qg11** [robhuijben/mod_darkmode#4]
Hi,

This is a great feature for you to make available, and we appreciate it!

Unfortunately, it isn't working for me.  I'm using Chrome, and have the Dark Mode switch (version 0.3.1) visible in the Status bar.  But clicking it produces no effect.  It's probably my error, so sorry to bother you ... but I can't see what I set up incorrectly.

Thanks,
Kip

**Comment by robhuijben** [comment]
Hi Kip, thank you for your issue. From Joomla! 5.1, the Dark Mode switch is integrated in Joomla! core. You can reach it in the user menu in the backend.

<img width="246" alt="Scherm­afbeelding 2024-04-30 om 12 15 24" src="https://github.com/robhuijben/mod_darkmode/assets/7040758/91ba8ba0-d9bb-4f08-8543-e785c24d9447">

If you find it more convenient to have the switch on the toolbar, I can take a look at that to refactor the switch and make it useful for Joomla! 5.1 and up as well.

**Comment by qg11** [comment]
Thanks Rob, 

That works great!  The switch wasn’t there for me because I updated from Joomla 4.4.4 directly to Joomla 5.1, but this video <https://www.youtube.com/watch?v=Vj7s1o6C_68>  from Tim Davis explained how to just save the administrator template to make it visible.  Thanks for letting me know that option existed and for giving users a method to accomplish it before it was integrated into the core. 

Cheers,

Kip

______________
